package pt.isel.mpd.v1718.li41n;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public String getGreeting() {
        return "SLB";
    }


    public class Inner {

    }
}


class Xpto {

}

interface Ypto {

}