/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.asynchttpclient.*;
import org.junit.Test;

import java.util.concurrent.ExecutionException;
import java.util.concurrent.Future;

import static org.junit.Assert.*;

public class HttpAsyncClientTest {

    private static final AsyncHttpClient asyncHttpClient = Dsl.asyncHttpClient();
    private static final String API_URL = "https://www.football-dto.org/v1/competitions";

    @Test
    public void shouldDoAGetRequest() throws ExecutionException, InterruptedException {
        final RequestBuilder requestBuilder = Dsl.get(API_URL);
        final Request request = requestBuilder.build();

        final Future<Response> responseListenableFuture = asyncHttpClient.executeRequest(request);

        final Response response = responseListenableFuture.get();

        System.out.println(response.getResponseBody());
    }
}
